language: generic
services:
  - docker

notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    - ADDITIONAL_DEBS="apt-utils git-core openssh-client openssh-server curl"
    - CATKIN_LINT=pedantic
    - NOT_TEST_DOWNSTREAM=true
    - PYLINT_ARGS="--output-format=parseable --errors-only --ignored-modules=catkin_pkg.python_setup,lxml.etree,lxml.builder,matplotlib,numpy,progressbar,rospkg,six.moves.http_client,tf2_ros,yaml"
    - PYLINT2_CHECK=true  # pylint2 for kinetic, pylint3 for noetic
    - PYLINT3_CHECK=false
    - PARALLEL_TESTS=false
    - ROS_REPO=ros
    - VERBOSE_OUTPUT=false
    - VERBOSE_TESTS=true
  matrix:
    - ROS_DISTRO=kinetic
    - ROS_DISTRO=melodic
    - ROS_DISTRO=noetic
install:
  - git clone --quiet --depth 1 https://github.com/fmessmer/industrial_ci.git .industrial_ci -b master_pylint
script:
  - .industrial_ci/travis.sh
