name: CI

on:
  push:
  pull_request:
#  schedule:
#    - cron: "0 23 * * *" # everyday at 11pm
  

jobs:
  industrial_ci:
    timeout-minutes: 30
    env:
      CATKIN_LINT: pedantic
      NOT_TEST_DOWNSTREAM: true
      PYLINT_ARGS: "--output-format=parseable --errors-only --ignored-modules=catkin_pkg.python_setup,lxml.etree,lxml.builder,matplotlib,numpy,progressbar,rospkg,six.moves.http_client,tf2_ros,yaml"
      PYLINT2_CHECK: true
      PYLINT3_CHECK: true
      PARALLEL_TESTS: true
      ROS_REPO: ros
      VERBOSE_OUTPUT: false
      VERBOSE_TESTS: true
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: kinetic}
          - {ROS_DISTRO: melodic}
          - {ROS_DISTRO: noetic}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'fmessmer/industrial_ci@master_pylint'
        env: ${{matrix.env}}
